FROM python:3.12 -slim 

WORKDIR /app

### Created the working directory for the app. 

COPY churn_fastapi/fastrequirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
