services:
  fastapi:
    build: 
      context: . 
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-container

    ports: 
     - "8000:8000"
    networks:
     - app-network 

  streamlit:
    build:
      context: . 
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-container
    ports:
     - "8501:8501"
    depends_on: 
     - fastapi 
    networks:
     - app-network 

