FROM python:3.12-slim

WORKDIR /streamlit 

COPY /app/streamlitrequirementx.txt /streamlit/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt 

COPY /app/app.py /streamlit

EXPOSE 8501

